/*
 * File: app/store/MenuDataViewStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.store.MenuDataViewStore', {
    extend: 'Ext.data.Store',

    requires: [
        'app.model.MenuDataViewModel'
    ],

    config: {
        data: [
            {
                image: 'resources/images/rc_icon.png',
                label: '下线入库'
            },
            {
                image: 'resources/images/rc_icon.png',
                label: '酸轧入库'
            },
            {
                image: 'resources/images/ck_icon.png',
                label: '原料出库'
            },
            {
                image: 'resources/images/ck_icon.png',
                label: '成品出库'
            },
            {
                image: 'resources/images/dd_icon.png',
                label: '扫码倒垛'
            },
            {
                image: 'resources/images/pd_icon.png',
                label: '盘库确认'
            },
            {
                image: 'resources/images/wq_icon.png',
                label: '成品接收'
            },
            {
                image: 'resources/images/hd_icon.png',
                label: '标签核对'
            },
            {
                image: 'resources/images/hd_icon.png',
                label: '有计划投料'
            },
            {
                image: 'resources/images/hd_icon.png',
                label: '无计划投料'
            },
            {
                image: 'resources/images/hd_icon.png',
                label: '卸料回库'
            },
            {
                image: 'resources/images/hd_icon.png',
                label: '发运备料'
            }
        ],
        model: 'app.model.MenuDataViewModel',
        storeId: 'MenuDataViewStore'
    }
});