/*
 * File: app/view/PLTCMPutawayView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.FuCaiTurnStoreView', {
    extend: 'Ext.Container',
    alias: 'widget.fuCaiTurnStoreView',

    requires: [
        'Ext.Container',
        'Ext.Spacer',
        'Ext.Button',
        'Ext.field.Select'
    ],

    config: {
        id: 'fuCaiTurnStoreView',
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                height: 80,
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        cls: 'menu_view_bg',
                        height: 80,
                        itemId: 'titleLayout',
                        padding: '0 20',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: [
                                    'base_font_family',
                                    'title_font_size',
                                    'title_cls'
                                ],
                                html: '辅材转库'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 80,
                        itemId: 'buttonLayout',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer1',
                                margin: '0 0 0 10',
                                minWidth: 70,
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            component.element.on('tap',function(){
                                                var root = Ext.getCmp('rootView');
                                                root.pop();
                                            });

                                        },
                                        event: 'initialize'
                                    }
                                ],
                                items: [
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                html: '<'
                                            },
                                            {
                                                xtype: 'container',
                                                html: '返回'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                cls: 'white_bg',
                padding: '10% 2%',
                scrollable: 'vertical',
                layout: {
                    type: 'vbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '批次号',
                                width: 100
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    //'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'a',
                                        clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                //hidden: true,
                                itemId: 'mybutton4',
                                text: '识别'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '物料编码',
                                width: 100
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: 'margin_content',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'b',
                                        clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '重量列表',
                                width: 100
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: 'margin_content',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'c',
                                        clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        //hidden : true,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '原成本中心',
                                width: 100
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    //'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'sampleStatus',
                                        //clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true,
                                        options: [
                                            {
                                                text: '',
                                                value: ''
                                            },
                                            {
                                                text: '测试2',
                                                value: '2'
                                            },
                                            {
                                                text: '测试1',
                                                value: '1'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        //hidden : true,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '转入成本中心',
                                width: 100
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'sampleStatus',
                                        //clearIcon: false,
                                        inputCls: 'white_select_input',
                                        //readOnly: true
                                        options: [
                                            {
                                                text: '测试1',
                                                value: '1'
                                            },
                                            {
                                                text: '测试2',
                                                value: '2'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },

                    {
                        xtype: 'container',
                        height: 36,
                        hidden : true,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: 'sid',
                                width: 65
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: 'margin_content',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'sid',
                                        clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        cls: [
                            'menu_view_bg',
                            'base_font_family'
                        ],
                        itemId: 'mybutton5',
                        margin: '10 ',
                        width: '100%',
                        text: '转库'
                    }
                ]
            }
        ],
        listeners: [
            /*{
             fn: 'onMytextfield1Blur',
             event: 'blur',
             delegate: '#sampleId'
             },*/
            {
                fn: 'onMatIdClearicontap',
                event: 'clearicontap',
                delegate: '#sampleId'
            },
            {
                fn: 'onMybutton5Tap',
                event: 'tap',
                delegate: '#mybutton5'
            },
            {
                fn: 'onPutawayViewHide',
                event: 'hide'
            }
        ]
    },

    /**
     * 出口卷号失去焦点事件
     * @param textfield
     * @param e
     * @param eOpts
     */
    onMytextfield1Blur: function(textfield, e, eOpts) {
        var currentView = textfield.up('#checkSampleView');
        var myMatId = textfield.getValue();
        console.log('失去焦点:',myMatId);//5191400884600//3991006289100
        if (myMatId!==''&&myMatId!==null&&myMatId!==undefined) {
            Ext.Ajax.request({
                url:rootUrl+'/quality/qmSampleRecord/findRecordView.action',
                method:'POST',
                params: {
                    'qm.sampleId' : textfield.getValue()
                },
                success: function(conn, response, options, eOpts) {
                    console.log('success');
                    var text = conn.responseText;
                    var obj = Ext.decode(text);
                    console.log('conn = ',conn.responseText);
                    console.log('obj = ',obj);
                    if (obj.data.length>0) {
                        currentView.setData({
                            a:text
                        });

                        currentView.down('#matId').setValue(obj.data[0].matId);
                        currentView.down('#sampleLotNo').setValue(obj.data[0].sampleLotNo);
                        currentView.down('#createdDt').setValue(obj.data[0].createdDt);
                        currentView.down('#sampleStatus').setValue(obj.data[0].sampleStatus);
                        currentView.down('#sid').setValue(obj.data[0].sid);
                    } else {
                        if (Ext.os.is('Android')) {
                            notice('没有匹配的结果！',null,'错误','确定');
                        } else {
                            Ext.Msg.alert('错误','没有匹配的结果！',Ext.emptyFn);
                        }
                    }

                },
                failure: function(conn, response, options, eOpts) {
                    if (Ext.os.is('Android')) {
                        notice('连接异常！',null,'错误','确定');
                    } else {
                        Ext.Msg.alert('错误','连接异常！',Ext.emptyFn);
                    }

                }
            });
        } else {
            if (Ext.os.is('Android')) {
                notice('出口卷号不能为空！',null,'错误','确定');
            } else {
                Ext.Msg.alert('错误','钢卷号不能为空！',Ext.emptyFn);
            }

        }

    },

    onMatIdClearicontap: function(textfield, e, eOpts) {
        var currentView = textfield.up('#checkSampleView');
        currentView.down('#sampleId').setValue('');
        currentView.down('#matId').setValue('');
        currentView.down('#sampleLotNo').setValue('');
        currentView.down('#createdDt').setValue('');
        currentView.down('#sampleStatus').setValue('');
        currentView.down('#sid').setValue('');
    },

    /**
     * 送样按钮
     * @param button
     * @param e
     * @param eOpts
     */
    onMybutton5Tap: function(button, e, eOpts) {
        Ext.Msg.alert('提示','转库成功！！');
        return;

        var item = button.up('checkSampleView');
        var myMatId = item.down('#sampleId').getValue();
        if(myMatId==''||myMatId==null||myMatId==undefined) {
            if (Ext.os.is('Android')) {
                notice('没有匹配的送样卷号不能送样！',null,'提示','确定');
            } else {
                Ext.Msg.alert('错误','没有匹配的送样卷号不能送样！',Ext.emptyFn);
            }
            return false;
        }
        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            fullscreen:true,
            message: '正在送样，请稍候......'
        });

        var obj = {};
        obj.sid= item.down('#sid').getValue();
        obj.sampleId= item.down('#sampleId').getValue();
        obj.matId= item.down('#matId').getValue();
        obj.sampleLotNo= item.down('#sampleLotNo').getValue();
        obj.createdDt= item.down('#createdDt').getValue();
        obj.sampleStatus= item.down('#sampleStatus').getValue();

        var str = Ext.encode(obj);
        console.log(str);
        Ext.Ajax.request({
            url:rootUrl+'/quality/qmSampleRecord/sendSample.action',
            method:'POST',
            jsonData : str,
            success: function(conn, response, options, eOpts) {
                Ext.Msg.alert('提示','送样成功！',Ext.emptyFn);
                // 清空数据
                item.down('#sid').setValue('');
                item.down('#sampleId').setValue('');
                item.down('#matId').setValue('');
                item.down('#sampleLotNo').setValue('');
                item.down('#createdDt').setValue('');
                item.down('#sampleStatus').setValue('');

                Ext.Viewport.setMasked(false);
            },
            failure: function(conn, response, options, eOpts) {
                var text = conn.responseText;
                var obj = Ext.decode(text);
                if (Ext.os.is('Android')) {
                    notice(obj.meta.message,null,'错误','确定');
                } else {
                    Ext.Msg.alert('错误',obj.meta.message,Ext.emptyFn);
                }
                Ext.Viewport.setMasked(false);
            }
        });

    },

    onWAREHOUSE_HALLSelectFieldChange1: function(selectfield, newValue, oldValue, eOpts) {

    },


    onPutawayViewHide: function(component, eOpts) {
        // component.destory();
    }

});