/*
 * File: app/view/PLTCMPutawayView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.FuCaiTurnStoreView', {
    extend: 'Ext.Container',
    alias: 'widget.fuCaiTurnStoreView',

    requires: [
        'Ext.Container',
        'Ext.Spacer',
        'Ext.Button',
        'Ext.field.Select'
    ],

    config: {
        id: 'fuCaiTurnStoreView',
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                height: 80,
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        cls: 'menu_view_bg',
                        height: 80,
                        itemId: 'titleLayout',
                        padding: '0 20',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: [
                                    'base_font_family',
                                    'title_font_size',
                                    'title_cls'
                                ],
                                html: '辅材转库'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 80,
                        itemId: 'buttonLayout',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'base_font_family',
                                height: '100%',
                                itemId: 'mycontainer1',
                                margin: '0 0 0 10',
                                minWidth: 70,
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                listeners: [
                                    {
                                        fn: function(component, eOpts) {
                                            component.element.on('tap',function(){
                                                var root = Ext.getCmp('rootView');
                                                root.pop();
                                            });

                                        },
                                        event: 'initialize'
                                    }
                                ],
                                items: [
                                    {
                                        xtype: 'container',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                html: '<'
                                            },
                                            {
                                                xtype: 'container',
                                                html: '返回'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                cls: 'white_bg',
                padding: '5% 2%',
                scrollable: 'vertical',
                layout: {
                    type: 'vbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '批次号',
                                width: 100
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'batchId',
                                        inputCls: 'white_select_input'
                                    },
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'scanInfo',
                                        inputCls: 'white_select_input',
                                        hidden: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '物料编码',
                                width: 100
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: 'margin_content',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'matNr',
                                        clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '物料描述',
                                width: 100
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: 'margin_content',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'matDesc',
                                        clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '标准重量(KG)',
                                width: 100
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: 'margin_content',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'weight',
                                        clearIcon: false,
                                        inputCls: 'color_select_input',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        //hidden : true,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '原成本中心',
                                width: 100
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'costCenterCode',
                                        inputCls: 'white_select_input',
                                        //usePicker: false,
                                        placeHolder: '请选择成本中心！',
                                        autoSelect: false,
                                        displayField: 'key',
                                        store: 'CostDataViewStore',
                                        valueField: 'value'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: 'blue_font',
                                html: '转入成本中心',
                                width: 100
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                cls: [
                                    'light_blue_border',
                                    'margin_content'
                                ],
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        cls: 'small_textfield_cls',
                                        itemId: 'turnCostCenterCode',
                                        inputCls: 'white_select_input',
                                        //usePicker: false,
                                        placeHolder: '请选择成本中心！',
                                        autoSelect: false,
                                        displayField: 'key',
                                        store: 'CostDataViewStore',
                                        valueField: 'value'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 36,
                        margin: '2 0',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                margin: '5 0 0 30 ',
                                itemId: 'clearBtn',
                                width: '40%',
                                text: '重置'
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'menu_view_bg',
                                    'base_font_family'
                                ],
                                margin: '5 0 0 10 ',
                                itemId: 'turnStore',
                                width: '40%',
                                text: '转库'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onClearBtnTap',
                event: 'tap',
                delegate: '#clearBtn'
            },
            {
                fn: 'onTurnStoreTap',
                event: 'tap',
                delegate: '#turnStore'
            },
            {
                fn: 'onPutawayViewHide',
                event: 'hide'
            },
            {
                fn:'onBatchIdBlur',
                event:'blur',
                delegate:'#batchId'
            }
        ]
    },

    initialize : function(){
        setTimeout(function(){
            var view = Ext.getCmp('fuCaiTurnStoreView');
            view.down('#batchId').focus();
        },500)
    },

    /**
     * 批次号失去焦点事件
     * @param textfield
     * @param e
     * @param eOpts
     */
    onBatchIdBlur: function (textfield, e, eOpts) {
        var item = textfield.up('#fuCaiTurnStoreView');
        var batchId = item.down("#batchId").getValue();
        var matNr = item.down("#matNr").getValue();
        item.down('#scanInfo').setValue(batchId);
        if (batchId!==''&&batchId!==null&&batchId!==undefined) {
            if(batchId!==''&&matNr==''){
                Ext.Viewport.setMasked({
                    xtype: 'loadmask',
                    fullscreen:true,
                    message: '请稍候......'
                });
                var str = batchId.split(',');
                item.down('#batchId').setValue(str[0].slice(4));
                item.down('#matNr').setValue(str[1].slice(5));
                Ext.Ajax.request({
                    url:rootUrl+'/pd/standard-weight/findByMatNr.action',
                    method:'POST',
                    params: {
                        matNr : item.down("#matNr").getValue()
                    },
                    success: function(conn, response, options, eOpts) {
                        Ext.Viewport.setMasked(false);
                        var result = Ext.decode(conn.responseText);
                        if (result.meta.success) {
                            item.down('#matDesc').setValue(result.data.matDesc);
                            item.down('#weight').setValue(result.data.standardWeight);
                        } else {
                            Ext.Msg.alert('提示','未查询到相关物料信息！');
                        }
                    },
                    failure: function(conn, response, options, eOpts) {
                        Ext.Viewport.setMasked(false);
                        Ext.Msg.alert('错误','网络连接异常，请重新扫码识别！');

                        item.down('#batchId').setValue('');
                        item.down('#matNr').setValue('');
                        item.down('#matDesc').setValue('');
                        item.down('#weight').setValue('');
                    }
                })
            }
        }else {
            item.down('#batchId').setValue('');
            item.down('#matNr').setValue('');
            item.down('#matDesc').setValue('');
            item.down('#weight').setValue('');
        }
    },

    /**
     * 转库按钮
     * @param button
     * @param e
     * @param eOpts
     */
    onTurnStoreTap: function(button, e, eOpts) {
        var item = button.up('#fuCaiTurnStoreView');
        var batchId= item.down('#batchId').getValue();
        var matNr= item.down('#matNr').getValue();
        var matDesc= item.down('#matDesc').getValue();
        var weight = item.down('#weight').getValue();
        var cost1 = item.down('#costCenterCode').getValue();
        var cost2 = item.down('#turnCostCenterCode').getValue();
        var scanInfo = item.down('#scanInfo').getValue();
        if(batchId == null || batchId == ''){
            Ext.Msg.alert('提示','批次号不能为空！');
            return;
        }
        if(matNr == null || matNr == ''){
            Ext.Msg.alert('提示','物料编码不能为空！');
            return;
        }
        if(weight == null || weight == ''){
            Ext.Msg.alert('提示','标准重量不能为空！');
            return;
        }
        if(cost1 == null || cost1 == ''){
            Ext.Msg.alert('提示','原成本中心不能为空！');
            return;
        }
        if(cost2 == null || cost2 == ''){
            Ext.Msg.alert('提示','转入成本中心不能为空！');
            return;
        }
        if(cost1 == cost2){
            Ext.Msg.alert('提示','原成本中心与转入成本中心一致!');
            return;
        }
        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            fullscreen:true,
            message: '请稍候......'
        });
        var obj = {};
        obj.batchId= batchId;
        obj.matNr= matNr;
        obj.matDesc= matDesc;
        obj.weight= weight;
        obj.costCenterCode= cost1;
        obj.turnCostCenterCode= cost2;
        obj.operateFlag= 3;
        obj.scanInfo= scanInfo;
        var str = Ext.encode(obj);
        Ext.Ajax.request({
            url:rootUrl+'/mat/stock-record/doForApp.action',//turnStore.action',
            method:'POST',
            jsonData : str,
            success: function(conn, response, options, eOpts) {
                var result = Ext.JSON.decode(conn.responseText);
                if (result.meta.success) {
                    Ext.Viewport.setMasked(false);
                    Ext.Msg.alert('提示','转库成功!');

                }else{
                    Ext.Viewport.setMasked(false);
                    Ext.Msg.alert('提示','转库失败:' + result.meta.message);
                }
                item.down('#batchId').setValue('');
                item.down('#matNr').setValue('');
                item.down('#matDesc').setValue('');
                item.down('#weight').setValue('');
            },
            failure: function(conn, response, options, eOpts) {
                Ext.Viewport.setMasked(false);
                Ext.Msg.alert('错误信息','网络中断或无连接.');
            }
        });

    },

    /**
     * 重置按钮
     * @param button
     * @param e
     * @param eOpts
     */
    onClearBtnTap: function(button, e, eOpts) {
        var item = button.up('#fuCaiTurnStoreView');
        item.down('#batchId').setValue('');
        item.down('#matNr').setValue('');
        item.down('#matDesc').setValue('');
        item.down('#matDesc').setValue('');
        item.down('#weight').setValue('');
    },

    onPutawayViewHide: function(component, eOpts) {
        // component.destory();
    }

});