/*
 * File: app/view/LoginView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.LoginView', {
    extend: 'Ext.Container',
    alias: 'widget.loginview',

    requires: [
        'Ext.Container',
        'Ext.Img',
        'Ext.field.Password',
        'Ext.field.Select',
        'Ext.Button'
    ],

    config: {
        cls: 'login_view_bg',
        id: 'loginView',
        layout: {
            type: 'vbox',
            align: 'center',
            pack: 'center'
        },
        items: [
            {
                xtype: 'image',
                //src: 'resources/images/logo.png',
                width:200,
                height:100,
                margin: '0 0 30 0'
            },
            {
                xtype:'label',
                html:'<span style="font-size: 34px;color: blue;">首钢PES系统</span>',
                margin: '0 0 10 0'
            },
            {
                xtype: 'fieldset',
                width:320,
                title: '用户登录',
                items: [
                    {
                        xtype: 'container',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'image',
                                height: 20,
                                width: 20,
                                src: 'resources/images/username_icon.png'
                            },
                            {
                                xtype: 'textfield',
                                itemId: 'userName'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'image',
                                height: 20,
                                width: 20,
                                src: 'resources/images/password_icon.png'
                            },
                            {
                                xtype: 'passwordfield',
                                itemId: 'passWord'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'image',
                                height: 20,
                                width: 20,
                                src: 'resources/images/time.png'
                            },
                            {
                                xtype: 'selectfield',
                                options: [
                                    {
                                        text: '白班',
                                        value: 'first'
                                    },
                                    {
                                        text: '中班',
                                        value: 'second'
                                    },
                                    {
                                        text: '晚班',
                                        value: 'third'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'image',
                                height: 20,
                                width: 20,
                                src: 'resources/images/classes.png'
                            },
                            {
                                xtype: 'selectfield',
                                // label: '班次',
                                itemId: 'crewSelect',
                                options: [
                                    {
                                        text: '甲班',
                                        value: '1'
                                    },
                                    {
                                        text: '乙班',
                                        value: '2'
                                    },
                                    {
                                        text: '丙班',
                                        value: '3'
                                    },
                                    {
                                        text: '丁班',
                                        value: '4'
                                    }
                                ],
                                usePicker: false
                            }
                        ]
                    },
                ]
            },
            {
                xtype: 'button',
                itemId: 'loginButton',
                text: ' 登 录 系 统'
            },
            {
                xtype: 'container',
                docked:'bottom',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype:'label',
                        html:'<span style="font-size: 12px;color: white;"><center>©Copyright&nbsp;&nbsp;北京首钢自动化信息技术有限公司信息事业部&nbsp;&nbsp;</center></span>'
                    }/*,
                    {
                        xtype: 'button',
                        itemId: 'mybutton2',
                        cls:'setting',
                        width:35
                    }*/
                ]
            }
        ],
        listeners: [
            {
                fn: 'onLoginButtonTap',
                event: 'tap',
                delegate: '#loginButton'
            }/*,
            {
                fn: 'onMybutton2Tap',
                event: 'tap',
                delegate: '#mybutton2'
            }*/
        ]
    },

    decodeJSON : function(text) {
        var result = Ext.JSON.decode(text, true);

        if (!result) {
            result = {};
            result.meta = {};
            result.meta.success = false;
            result.meta.msg = text;
        }
        return result;
    },

    onLoginButtonTap: function(button, e, eOpts) {
        var me = this;
        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            fullscreen:true,
            message: '请稍候......'
        });
        var loginView = button.up('#loginView');
        var userName = loginView.down('#userName').getValue();
        var passWord = loginView.down('#passWord').getValue();
        var crewId = loginView.down('#crewSelect').getValue() ;
        if (userName==''||passWord==''){
            Ext.Viewport.setMasked(false);
            Ext.Msg.alert('错误','用户名或密码不能为空！');
        }else{
            var menuView = Ext.create('app.view.MenuView');
            var root = Ext.getCmp('rootView');
            var nemuStore = Ext.getStore('MenuDataViewStore');
            nemuStore.removeAll();
            nemuStore.add({'image':'resources/images/ck_icon.png',
                'label':'辅材出库','RES_ID':'SL-MOBILE-01'});
            nemuStore.add({'image':'resources/images/dd_icon.png',
                'label':'辅材转库','RES_ID':'SL-MOBILE-02'});
            nemuStore.add({'image':'resources/images/ck_icon.png',
                'label':'锌锭出库','RES_ID':'SL-MOBILE-03'});
            nemuStore.add({'image':'resources/images/dd_icon.png',
                'label':'锌锭转库','RES_ID':'SL-MOBILE-04'});
            root.push(menuView);
            Ext.Viewport.setMasked(false);
            return;
        }





    },

    /*onMybutton2Tap: function(button, e, eOpts) {
        var root = Ext.getCmp('rootView');
        var serverSetting = Ext.create('app.view.ServerSetting');
        root.push(serverSetting);
    }*/

});