/*
 * File: app/view/MenuView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.MenuView', {
    extend: 'Ext.Container',
    alias: 'widget.menuview',

    requires: [
        'Ext.Button',
        'Ext.dataview.DataView'
    ],

    config: {
        // cls: 'menu_view_bg',
        id: 'menuView',
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                height: 80,
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        cls: [
                            'menu_item_bg'
                        ],
                        height: 80,
                        zIndex: 1,
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                cls: [
                                    'base_font_family',
                                    'title_font_size'
                                ],
                                html: '首页'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 80,
                        zIndex: 2,
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                flex: 1
                            },
                            {
                                xtype: 'container',
                                items: [
                                    {
                                        xtype: 'button',
                                        cls: [
                                            'menu_item_bg',
                                            'base_font_family'
                                        ],

                                        itemId: 'mybutton8',
                                        margin: '0 5 0 auto',
                                        text: '注销'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'dataview',
                flex: 1,
                itemId: 'menuDataView',
                padding: '2%',
                cls: 'menu_view_bg',
                scrollable: 'vertical',
                defaultType: 'menuDataItem',
                inline: true,
                store: 'MenuDataViewStore',
                useComponents: true
            }
        ],
        listeners: [
            {
                fn: 'onMybutton8Tap',
                event: 'tap',
                delegate: '#mybutton8'
            },
            {
                fn: 'onMenuDataViewItemTap',
                event: 'itemtap',
                delegate: '#menuDataView'
            },
            {
                fn: 'onMenuViewHide',
                event: 'hide'
            },
            {
                fn: 'onMenuViewDestroy',
                event: 'destroy'
            }
        ]
    },

    onMybutton8Tap: function(button, e, eOpts) {
        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            message: '请稍候......'
        });
        Ext.Ajax.request({
            url:rootUrl + '/ac/login/logout.action',
            success: function(conn, response, options, eOpts) {
                Ext.Viewport.setMasked(false);
            },
            failure: function(conn, response, options, eOpts) {
                Ext.Viewport.setMasked(false);
                Ext.Msg.alert('错误信息','网络中断或无连接.');
            }
        });

        var root = Ext.getCmp('rootView');
        root.pop();
    },

    onMenuDataViewItemTap: function(dataview, index, target, record, e, eOpts) {
        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            message: '请稍候......'
        });
        var label = record.get('RES_ID');
        var root = dataview.up('#root');
        var root = Ext.getCmp('rootView');
        var slide = Ext.create("Ext.fx.layout.card.Slide",{direction:"left"});
        //console.log('label = '+label);
        var targetView;

        setTimeout(function(){
            if ('SL-MOBILE-01' ===label) {
                targetView = Ext.create('app.view.FuCaiOutStoreView');
                root.push(targetView);
            }
            else if ('SL-MOBILE-02' ===label) {
                targetView = Ext.create('app.view.FuCaiTurnStoreView');
                root.push(targetView);
            }
            else if ('SL-MOBILE-03' ===label) {
                targetView = Ext.create('app.view.XinDingOutStoreView');
                root.push(targetView);
            }
            else if ('SL-MOBILE-04' ===label) {
                targetView = Ext.create('app.view.XinDingTurnStoreView');
                root.push(targetView);
            }
            Ext.Viewport.setMasked(false);
        },500);

    },

    onMenuViewHide: function(component, eOpts) {
        // component.destroy();
    },

    onMenuViewDestroy: function(eOpts) {
        console.log('destroy');
    }

});